export const FILM_ROLES = [
  'Actor',
  'Additional Camera Operator',
  'Additional Cam Op',
  'Assistant Director (AD)',
  '1st AD',
  '2nd AD',
  'Associate Producer',
  'Audio Engineer',
  'Audio/Lighting',
  'Camera Assistant',
  'Cinematographer',
  'Composer',
  'Creative Director',
  'Director',
  'Director of Photography (DP)',
  'Drone Pilot',
  'Editor',
  'Filmmaker',
  'Finance',
  'Gaffer',
  'Grip',
  'Music',
  'Narrator',
  'PA (Production Assistant)',
  'Photographer',
  'Producer',
  'Production Assistant',
  'Production Coordinator',
  'Production Designer',
  'Production Manager (PM)',
  'Screenwriter',
  'Scriptwriting',
  'Sound Engineer',
  'Spokesperson',
  'Videographer',
  'Writer',
] as const;

export type FilmRole = typeof FILM_ROLES[number];
